version: '3.8'
services:
  caddy:
    restart: always
    build:
      context: ./caddy
      dockerfile: ./caddy.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - '5173:5173'  # Ensure this port is exposed for internal communication
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      BROKER_URL: http://backend
      WDS_SOCKET_PORT: 0

  backend:
    build:
      context: ./backend
      dockerfile: ./backend.dockerfile
    restart: always
    ports:
      - '8080:8080'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST} # If you are using local database. Like PgAdmin or DBeaver. Use host.docker.internal in the .env file or ip address of the host machine.
      # DB_HOST: db # Uncomment this line if you are using a separate database container. Comment the line above. Uncomment the db service below.
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
  
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: ${DB_DATABASE}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - '5432:5432'
