version: '3.8'
services:
  caddy:
    restart: always
    build:
      context: ./caddy
      dockerfile: ./caddy.dockerfile
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - '80:80'
    depends_on:
      - backend
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend.dockerfile
    restart: unless-stopped
    ports:
      - '5173:5173'  # Ensure this port is exposed for internal communication
    volumes:
      - /app/node_modules
      - ./frontend:/app
    env_file: ./frontend/.env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./backend.dockerfile
      target: dev
    restart: always
    ports:
      - '8080:8080'
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    # depends_on:
    #   - db
  
  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: ${DB_DATABASE}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - ./db:/var/lib/postgresql/data
